version: "3"
services:

  nginx:
    build: 
      context: ./docker/nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    container_name: nginx
    networks:
      - trips

  php:
    build: 
      context: ./docker/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./html:/var/www/html
    container_name: php
    networks:
      - trips
      
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trips
      MYSQL_USER: trips
      MYSQL_PASSWORD: trips
    container_name: mysql
    networks:
      - trips

  node:
    image: node:lts
    volumes:
      - ./html:/var/www/html
    command: tail -f /dev/null
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    container_name: node
    networks:
      - trips

networks:
  trips: