controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

root:
    path: /
    defaults:
        _controller: App\Controller\TripController::index